export default {
  btnModalClose: document.querySelector('.modal-close'),
  ticketInfoContainer: document.querySelector('.ticket-info-container'),
  ticketModal: document.querySelector('.backdrop'),
  gallery: document.querySelector('.card-list'),
  countriesList: document.querySelector('.js-countries-form-input'),
  genresList: document.querySelector('.js-genres-form-input'),
  logo: document.querySelector('.logo'),
  form: document.getElementById('search'),
  pagination: document.querySelector('.tui-pagination'),
  countryMenu: document.querySelector('#country'),
  categoryMenu: document.querySelector('#category'),
  countryBtn: document.querySelector('.country-btn'),
  categoryBtn: document.querySelector('.category-btn'),
};
