export default {    
    btnModalClose: document.querySelector('.modal-close'),
    ticketInfoContainer: document.querySelector('.ticket-info-container'),
    ticketModal: document.querySelector('.backdrop'),
    gallery: document.querySelector('.card-list'),
    countriesList: document.getElementById('country'),
    genresList: document.getElementById('category'),
    searchInput: document.querySelector('.js-search-input'),
    logo: document.querySelector('.logo'),
    form: document.getElementById('search'),
    modalMoreInfo: document.querySelector('.more-info-list'),
    modalMoreInfoBtn: document.querySelector('.more-information'),
    pagination: document.querySelector('.tui-pagination'),
    countryMenu: document.querySelector('#country'),
    categoryMenu: document.querySelector('#category'),
    countryBtn: document.querySelector('.js-countryBtn'),
    categoryBtn: document.querySelector('.js-categoryBtn'),
    evtInfo: document.getElementById('info'),
    evtInfoMore: document.getElementById('more'),
    evtInfoLess: document.getElementById('less'),
    modalPrev: document.getElementById('p'),
    modalNext: document.getElementById('n')
}
